### ISSUE TITLE
crash when try to search

### ISSUE THREAD

**Issue by muhammadarif1** [mathisdt/sdbviewer#10]
i dont know this is can be a bug or no, just report it
step to reproduce 
-open the app 
- click setting
- than chose general
- than change song addres whit another web
- than go back and refresh and click search option and type any word and see if the app will crash 

recording of the buug
https://youtu.be/3LJd6-Db06M
log cat
```ACRA caught a NullPointerException for org.zephyrsoft.sdbviewer
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.zephyrsoft.sdbviewer.SongListActivity$SimpleItemRecyclerViewAdapter.filter(java.lang.String)' on a null object reference
	at org.zephyrsoft.sdbviewer.SongListActivity.applyFilter(SongListActivity.java:133)
	at org.zephyrsoft.sdbviewer.SongListActivity.handleSearchText(SongListActivity.java:127)
	at org.zephyrsoft.sdbviewer.SongListActivity.access$000(SongListActivity.java:41)
	at org.zephyrsoft.sdbviewer.SongListActivity$1.onQueryTextChange(SongListActivity.java:117)
	at android.widget.SearchView.onTextChanged(SearchView.java:1228)
	at android.widget.SearchView.access$2000(SearchView.java:98)
	at android.widget.SearchView$10.onTextChanged(SearchView.java:1712)
	at android.widget.TextView.sendOnTextChanged(TextView.java:8190)
	at android.widget.TextView.handleTextChanged(TextView.java:8253)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10069)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:982)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:528)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:465)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:693)
	at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:453)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by mathisdt** [comment]
Hi @muhammadarif1, thanks for providing feedback! I was quickly able to identify the issue because of your good error documentation. The fix is not released yet, but it will be with the next version.

**Comment by muhammadarif1** [comment]
can you labeled this as a bug?

**Comment by muhammadarif1** [comment]
thank you sir
